### ISSUE TITLE
Initiation of Monorepo

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#1]
Open discussion for the transition to a monorepo for our web/ui components.

## Current Plan
- [x] Move all UI components under new `web-components` repo (@dselman) — essentially done
- [x] Align version numbers / setup for Travis and npm deploy/publish (@jeromesimeon)
- [x] Do an unstable release to check that the packages can be consumed by users
  - [x] Including the new rollup packaging, etc
- [x] Decide when to officially publish
  - [x] Need to copy again the code from latest `master` in each UI component repos (@irmerk)
  - This could go nicely with the planned release of `markdown-editor` and `cicero-ui`
  - Instead of releasing, publish the first iteration of the new library
  - Point everyone to the new repo
- [x] Loose git history but migrate all issues under new repo (@irmerk)
- [x] Archive old repos

## Open Questions
- Component naming format? 
  - As is now?
  - New? e.g., `@accordproject/wc-cicero` `@accordproject/wc-concerto` `@accordproject/wc-markdown-editor`
  - Are we happy with `web-components`? A different name could possibly make for easier component naming
- What do we do with old demos, delete?
- Does it happen before or before `Slate57` components release?
- For versioning, does this mean we would start at `0.1.0` or continue on?
  - If we do not rename we have to increment
  - Highest is `concerto-ui` `0.80`+ so might be `0.90`
  - If new names we can do anything
- …?

**Comment by irmerk** [comment]
I like using the suggestion (`@accordproject/wc-cicero` `@accordproject/wc-concerto `@accordproject/wc-markdown-editor`) much more than keeping the names the same. I also prefer resetting the versioning, with pointers to archived repositories.

However, not sure I'm sold on `web-components` / `wc-...` Some other ideas:
- `shards` - `@accordproject/shard-cicero`
- `tools` - `@accordproject/tool-cicero`
- `web` - `@accordproject/web-cicero`
- `desktop` - `@accordproject/desk-cicero`
- `accordstrap` - `@accordproject/strap-cicero`
- `suite` - `@accordproject/suite-cicero`
- `fabric` - `@accordproject/fabric-cicero`
- `axial` - `@accordproject/axial-cicero`
- `visio` - `@accordproject/visio-cicero`
- `visus` - `@accordproject/visus-cicero`
- `proviso` - `@accordproject/proviso-cicero`
- `videre` - `@accordproject/videre-cicero`

**Comment by irmerk** [comment]
My strongest preference is for `videre`, `solis`, `monstro`, `attuor`, or `capio`

**Comment by mttrbrts** [comment]
I'm not keen on doubling the latinate names, it makes it more difficult to understand what the modules do. We are using latinate names for top-level projects, most of these refer to tools that are conceptually related to those projects.

My vote would be for something more descriptive, e.g. `cicero-web`, `cicero-ui`,

**Comment by jeromesimeon** [comment]
An example of naming packages: https://github.com/marmelab/react-admin/tree/master/packages

```
@accordproject/ui-cicero
@accordproject/ui-concerto-core
@accordproject/ui-concerto-forms
@accordproject/ui-text-editor
@accordproject/ui-rich-text-editor
```

**Comment by irmerk** [comment]
I like that @jeromesimeon

**Comment by irmerk** [comment]
Will be adjusting the published packages to:

- `@accordproject/ui-concerto`
- `@accordproject/ui-markdown-editor`
- `@accordproject/ui-contract-editor`
- `@accordproject/ui-components` (`error`, `library`, `navigation`, `text-editor`)
