### ISSUE TITLE
new paragraph after h1,h2,h3 should be normal text

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#102]
# Feature Request 🛍️

When a user is writing an h1, h2, or h3 and presses enter to make a new paragraph, the new paragraph should be normal text.

see how Google docs has this functionality in this video:
https://www.loom.com/share/c45fcd3bd1374217823b6e447fd0d1d5

## Use Case
User is writing a heading and wants to write some text under that heading. They press enter and the text under the heading is automatically set to normal text.

When a user presses enter, it creates a new paragraph which has normal paragraph style. If a user presses shift+enter, a new line is created within the same paragraph, which will be the same paragraph style as the first line in the paragraph.

**Comment by Michael-Grover** [comment]
I am bumping this one, I think it's important. Having to select "normal" text after typing every headline is tedious.

**Comment by jeromesimeon** [comment]
> I am bumping this one, I think it's important. Having to select "normal" text after typing every headline is tedious.

Do we think someone might still want a way to do new lines inside a title? You can definitely do it in markdown.

Maybe:
- default should be a new paragraph after the title
- shift-return should stay within the title (in a way symmetric to shift-return for hard breaks inside a paragraph)

**Comment by jeromesimeon** [comment]
<img width="1186" alt="Screenshot 2020-07-23 at 2 53 45 PM" src="https://user-images.githubusercontent.com/670099/88326736-59dd8e00-ccf4-11ea-9b67-53f8764c5cb0.png">

**Comment by Michael-Grover** [comment]
I think shift+return should create a line break within the header paragraph and keep the header formatting. If a user presses return, that should create a new paragraph that is normal text

**Comment by jeromesimeon** [comment]
> I think shift+return should create a line break within the header paragraph and keep the header formatting. If a user presses return, that should create a new paragraph that is normal text

I like that

**Comment by amanda-ariyaratne** [comment]
Hello, Is this issue up for grabs?

**Comment by Michael-Grover** [comment]
> Hello, Is this issue up for grabs?

Yup, I just assigned it to you. Thanks!
