### ISSUE TITLE
Make the preview headings in the style dropdown reflect the style of those headings

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#103]
# Discussion 🗣
Currently the heading previews in the style dropdown do not reflect the actual appearance of headings when they are added in the contract text. These previews should give the user an accurate preview of what the heading should look like in the document. 

This should remain so even when people who extend this component change the heading styles for their particular apps. They should be linked so if the heading styling changes, the preview of it in the styling dropdown changes too. So when if change the heading styling to be sans-serif instead of a serif font, the dropdown should ideally reflect that.

Current:
![image](https://user-images.githubusercontent.com/40569793/82707881-f29b5300-9c4a-11ea-9fe4-e0aada2f3b0c.png)

doesn't match headings in text:
![image](https://user-images.githubusercontent.com/40569793/82708044-545bbd00-9c4b-11ea-9830-af87aeb154f0.png)

**Comment by conste11ations** [comment]
Hi! I created a pull request in hopes this helps you with the issue you have raised. Took a stab at assuming how people would ideally extend these components (assumed the constants would be updated because there are default styles already there), please let me know if incorrect!
