### ISSUE TITLE
Possible to split paragraphs in half with drag and drop

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#120]
# Bug Report 🐛
Dragging and dropping a Clause Template into the margins to the left or right of a paragraph allows the Clause Template to split the paragraph in half.

## Expected Behavior
The Clause Template should be placed before or after the paragraph

## Current Behavior
https://www.loom.com/share/329b20b14ecf4cd9854d31dba93b5e92

## Steps to Reproduce
1. drag Clause Template
2. drop into margin in the middle of paragraph
3. paragraph is split in half

**Comment by irmerk** [comment]
This can be undone and also fixed manually, so not super serious.

@DianaLease playing with the CSS in the demo, I think this is because the drop point is in the `padding` of `ap-rich-text-editor`. Could we maybe just switch to `margin` instead?

**Comment by gatij10** [comment]
@Michael-Grover is this issue still open? I would like to work on it.

**Comment by irmerk** [comment]
@gatij10 test it out in the live Storybook and see if the issue still exists.

**Comment by gatij10** [comment]
@irmerk I tested it out in the live storybook, looks like the issue still exists. I will try to solve it.

**Comment by Cronus1007** [comment]
@Michael-Grover @irmerk Since the issue exists in the live storybook so shall I work upon this issue.

**Comment by Cronus1007** [comment]
> @DianaLease playing with the CSS in the demo, I think this is because the drop point is in the `padding` of `ap-rich-text-editor`. Could we maybe just switch to `margin` instead?

@irmerk This one is not working.The problem may arise bcoz there is not any type of function which handles drop. So what I intend to do is write the handleDrop function to handle the Drop. Does it sound good to proceed?

**Comment by irmerk** [comment]
I think @DianaLease is more familiar with this code and can be of more help at the moment. I won't have a chance to look into this for a bit.

**Comment by DianaLease** [comment]
hi @Cronus1007 . The logic that handles drop for the contract editor is here: https://github.com/accordproject/web-components/blob/5c92ecbe046af74aabdeed8be2990c28cb5fd9c6/packages/ui-contract-editor/src/ContractEditor/index.js#L199

This function is passed to the `MarkdownEditor` as a prop where it gets called whenever a drop event fired.

**Comment by Michael-Grover** [comment]
I'm cleaning up old issues I created, and it looks like this one hasn't been resolved, so I'm keeping it open in case a hacktoberfest 2021 participant wants to give it a shot

**Comment by vikasazad** [comment]
Hi @irmerk  I wanted to work on this..?

**Comment by TC5022** [comment]
Hello @irmerk , may I work on this issue, if it's still open?

**Comment by vikasazad** [comment]
Hi @irmerk @DianaLease where i can ask doubts regarding the problem cause slack link is offline...?

**Comment by Michael-Grover** [comment]
Hi @vikasazad , the Accord Project now uses Discord instead of Slack, you can join at this link: https://discord.gg/xPPT3gVt 

If you have questions about this issue, you can add them as a reply to this github issue

**Comment by irmerk** [comment]
I'll assign this to someone when there is a work in progress PR on it.

**Comment by anmode** [comment]
Hey! This is issue still exist in the storybook live demo and I had checked the code base of contract editor. I am unable to identify the what causing this issue, need some guidance please

**Comment by pritesh299** [comment]
Hey! I checked this is issue still exist in the storybook live demo and since it is not assigned to anyone, I have worked on it.
observed Behavior: [link](https://www.loom.com/share/6bd037d8267f466d833fa9e91913b6a9?sid=1912f6c3-9c8b-41bf-9b22-d370ab260074)
Fixed behavior:[Link](https://www.loom.com/share/6bb61ed53f084d6c993066e49a3a4222?sid=7aee13d5-f0ca-42e4-8626-93e87598836d)
