### ISSUE TITLE
ReadOnly mode should provide a simplified & compact rendering of the form.

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/web-components#13]
**Is your feature request related to a problem? Please describe.**
As discussed in https://github.com/accordproject/concerto-ui/pull/54, when the `readOnly` prop is true, it would be convenient for the form fields to be more compact.

**Describe the solution you'd like**
For example, currently, 
- the buttons and dropdown fields appear as disabled input fields, however it would be more natural for them to be readOnly input fields

**Describe alternatives you've considered**
Alternatively, all of the fields could be replaced with labels. This is a more fundamental change, and the form would no longer be "a form". This could be an alternative prop, e.g. `noFields`, `textOnly` ?

**Comment by Cronus1007** [comment]
@mttrbrts Shall I work upon this issue.

**Comment by irmerk** [comment]
I'm currently working on this Issue

**Comment by TC5022** [comment]
if this issue is still open, may I work on it @irmerk ?

**Comment by irmerk** [comment]
Go for it.
