### ISSUE TITLE
DateTime Objects cause ui-concerto to crash

### ISSUE THREAD

**Issue by discochance** [accordproject/web-components#131]
# Bug Report 🐛

When using a modelfile which contains a `DateTime` Attribute, the form crashes either when modifying the sample value or instantly. 
## Expected Behavior

I expect the form generator to generate the form correctly and either generate a sample value or not, depending on the options. Furthermore it should not crash when wrong values are inserted, as this can happen while typing.
## Current Behavior

The form generator crashes with Error 130:
https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=
Sometimes only the error message "Invalid JSON instance provided" is displayed.
## Possible Solution

Maybe something to do with input checking? 
## Steps to Reproduce

1. visit https://ap-web-components.netlify.app/?path=/story/concerto-form--demo
2. under  Knobs > Model change an attribute of `concept Address`to `DateTime`
3. If Form renders, try to change the value displayed in it.
4. observe error message

## Context (Environment)

I am using web-components to implement contracts via a web application on HLF. This issue prevents me from updating from `concerto-ui-core: 0.82.8`. 
### Desktop
 - OS: Arch linux, Windows
 - Browser: Firefox, Chromium
 - Version: 78, 83.0

## Detailed Description

In my eyes, `ui-concerto` should be able to render every primitive type and allow users to change their values, even if they temporarily are in an invalid format, like a DateTime String missing some character because the user is still typing. An indication of the value being incorrect is okay, as long as the user is not prevented from completing the value, by  i.e. replacing the wrong value with something else.

**Comment by jeromesimeon** [comment]
I can reproduce on Safari, following @discochance 's instructions. Below is a snapshot.

<img width="872" alt="Screenshot 2020-07-01 at 11 13 47 AM" src="https://user-images.githubusercontent.com/670099/86260968-f85e4f80-bb8b-11ea-8c8e-407a4905fedb.png">
