### ISSUE TITLE
Error when transform block with mark to list

### ISSUE THREAD

**Issue by SirMoustache** [accordproject/web-components#134]
# Bug Report 🐛

## Expected Behavior
There should be no errors.

## Current Behavior
A wild Error appears

## Steps to Reproduce
1. Go to https://ap-web-components.netlify.app/?path=/story/markdown-editor--demo
2. Select the first paragraph *AFTER* any marked block (bold, italics)
3. Try to change it to UL  or OL
4. See an error in the console
![image](https://user-images.githubusercontent.com/8169559/86352815-1355c000-bc6f-11ea-8e78-30d7d4d90c78.png)

### Desktop
Slate: 0.58.3
Browser: Chrome 
OS: Windows 10

**Comment by hohooio823** [comment]
can you assign me on it

**Comment by dselman** [comment]
> can you assign me on it

Done

**Comment by hohooio823** [comment]
Solved , needs to test it and make a pull request
