### ISSUE TITLE
Remove quotation marks from around string variables

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#136]
Remove quotation marks from string variables. From a user's perspective, the variables don't need quotation marks to distinguish them from the rest of the text, because there is already a border around the variable. 

![image](https://user-images.githubusercontent.com/40569793/86391815-65471780-bc68-11ea-8e2f-2b17bc54b994.png)

**Comment by jeromesimeon** [comment]
Fixed and tested in #123
