### ISSUE TITLE
Reduce height of drag and drop handle so short clauses don't have large space

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#137]
### Feature Request 🛍️
Clauses with 1-3 lines of text have an awkward space at the bottom caused by the drag and drop handle. We can mitigate this by compressing the drag and drop handle.

the drag and drop buttons in the UI are spaced further apart than they are in the mockup. Making the buttons closer together like in the mockup should mitigate some of this issue.
![image](https://user-images.githubusercontent.com/40569793/86400208-359f0c00-bc76-11ea-80b9-364e8da614f1.png)

mockup:
![image](https://user-images.githubusercontent.com/40569793/86400224-3a63c000-bc76-11ea-9a97-97d6df9d1b96.png)

PM me for invision link to mockup

reducing this space only on very small clauses could help
![image](https://user-images.githubusercontent.com/40569793/86400287-59625200-bc76-11ea-9edb-633e850653ca.png)

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I would like to give it a try.

**Comment by Michael-Grover** [comment]
@K-Kumar-01 thanks, I've assigned it to you. Let me know if you need a mockup in invision, or if the screenshot is sufficient

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I have some doubts related to this issue.

Original Image
![Screenshot from 2021-02-25 14-02-30](https://user-images.githubusercontent.com/59891164/109125529-2c692f00-7772-11eb-80e8-032df5ac9d35.png)
Some changes in the css styles of dragwrapper(Causing the template to look a bit smaller than above)
![Screenshot from 2021-02-25 14-02-25](https://user-images.githubusercontent.com/59891164/109125536-2ecb8900-7772-11eb-9f94-aae47337ef7f.png)
Aligning the content itself to center to cover up the spaces
![Screenshot from 2021-02-25 14-02-22](https://user-images.githubusercontent.com/59891164/109125543-30954c80-7772-11eb-9b55-cad7a997ce2b.png)

Reducing the height is good but it is also limited to a particular limit beyond which it won't look good.
So can we go with the 3rd option or try changing more styles?

**Comment by Michael-Grover** [comment]
I think making the space between the drag-and-drop buttons more like this (image) will be enough to close this issue. I think very short clauses having some extra space at the bottom will be unavoidable, but at least we can reduce the extra space.

![image](https://user-images.githubusercontent.com/40569793/109215267-eebfd280-7780-11eb-9b7e-c6a34bcd2329.png)

**Comment by Michael-Grover** [comment]
@K-Kumar-01  you mentioned changing more styles, do you have anything in mind?

**Comment by K-Kumar-01** [comment]
> @K-Kumar-01 you mentioned changing more styles, do you have anything in mind?

@Michael-Grover 
I have tried some more styling. The images are as follows:
![Screenshot from 2021-02-27 11-17-34](https://user-images.githubusercontent.com/59891164/109376878-71fe3700-78ed-11eb-8d14-e94146676253.png)
![Screenshot from 2021-02-27 11-04-06](https://user-images.githubusercontent.com/59891164/109376883-77f41800-78ed-11eb-9e18-e346bd01a75f.png)
![Screenshot from 2021-02-27 11-03-52](https://user-images.githubusercontent.com/59891164/109376886-7a567200-78ed-11eb-8305-837e7a1371c4.png)
![Screenshot from 2021-02-27 11-03-31](https://user-images.githubusercontent.com/59891164/109376889-7c203580-78ed-11eb-8e99-21522f564eab.png)
![Screenshot from 2021-02-27 11-00-20](https://user-images.githubusercontent.com/59891164/109376898-84787080-78ed-11eb-92ef-586daeb5747c.png)

The 1st image is the closest I could bring to resolve the issue.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
any updates here?

**Comment by Michael-Grover** [comment]
I agree the first one looks the best, but it looks like the dots are off-center 
![image](https://user-images.githubusercontent.com/40569793/109665649-65235280-7b3c-11eb-8078-bad41fe8d5da.png)

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I changed some SVG styling so it might be the case. If the dots are centered, then can we go with this one?

**Comment by Michael-Grover** [comment]
@K-Kumar-01 that sounds good, thanks 👍

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
It is the latest styling change which I applied.
![Screenshot from 2021-03-03 00-37-03](https://user-images.githubusercontent.com/59891164/109701102-a6594800-7bb8-11eb-803b-c5863825acb9.png)
Should I open the PR with this one?

**Comment by Michael-Grover** [comment]
Yeah, that looks good for a PR

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I have opened a PR. Let me know if there are any changes required.
