### ISSUE TITLE
Error while deleting whole text from concerto form field

### ISSUE THREAD

**Issue by shift-a-bit** [accordproject/web-components#141]
# Bug Report 🐛

## Expected Behavior

One can remove text from form field by pressing backspace.

## Current Behavior

When we try to remove character with backspace it works until there is only on character on field. After reaching to one character there is error in console . This works fine if someone selects whole text and start typing.

## Steps to Reproduce

1. git clone https://github.com/accordproject/web-components-starter.git
2. npm run start 
3. Go to concerto form 
4. Try to delete all characters

![concerto-issue](https://user-images.githubusercontent.com/17876812/86444881-11ebcc80-bd2f-11ea-84b7-a6a2222d1c0c.JPG)

**Comment by DianaLease** [comment]
Hi @shift-a-bit! I've updated web-components-starter with a version of ui-concerto which fixes this bug. The version is `0.93.2-20200702221818`.
