### ISSUE TITLE
Pressing Cmd+C does not always copy selection

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#142]
# Bug Report 🐛
Pressing cmd+c while highlighting text does not always copy the selection.

## Expected Behavior
When I highlight text and press cmd+c, and then move my cursor somewhere else and press cmd+v, the text should be pasted

## Current Behavior
Sometimes when I copy text and paste it, the previously highlighted text is pasted instead of what I just copied. I have to select the text and copy it again to be able to paste it. This appears to only be happening in the contract editor, not markdown editor

## Steps to Reproduce
1. Copy some text to your clipboard, like a URL
2. Go to contract editor demo in storybook https://ap-web-components.netlify.app/?path=/docs/contract-editor--contract-editor
3. triple click on a line of text to select the entire line
4. Press cmd+c to copy
5. move your text cursor somewhere else in the contract
6. Press cmd + v to paste
7. See that what you just copied is not what was pasted

video:
https://www.loom.com/share/864db3caebb64b79aeaf414eaede57ec 

### Desktop
 - OS: macOS
 - Browser: Chrome

**Comment by Cronus1007** [comment]
@Michael-Grover It is working fine with Windows as well as Linux.This issue is specific to MacOs.

**Comment by Michael-Grover** [comment]
I can't replicate this bug on Mac so I'm closing it
