### ISSUE TITLE
WYSIWYG between Slate and PDF

### ISSUE THREAD

**Issue by dselman** [accordproject/web-components#146]
# Feature Request 🛍️
markdown-pdf centers H1s when rendering to PDF, so it would be useful to do the same in Slate.
It would also be good to review the default font sizes to ensure that they are aligned between Slate and PDF so that they are roughly equivalent at common screen resolutions.

Question: do we want to sync the choice of serif/sans between Slate and PDF?

Styles for PDF are here:
https://github.com/accordproject/markdown-transform/blob/master/packages/markdown-pdf/src/PdfTransformer.js#L173
## Use Case
Improve WYSIWYG between Slate editor and rendered PDF.

**Comment by Udbhavbisarya23** [comment]
@dselman I would like to work on this issue. Is it still open?

**Comment by jeromesimeon** [comment]
@Udbhavbisarya23 Still open!

**Comment by Udbhavbisarya23** [comment]
@dselman @jeromesimeon @irmerk I have opened a pr with the changes required. Let me know if i need to make any more changes
