### ISSUE TITLE
empty string variable

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#150]
# Feature Request 🛍️
Because we removed the “”, it looks like a user can no longer delete the first character of a string variable by pressing backspace. This makes it really annoying to change the text of a string variable (unless you happen to want to change the variable to a different string that has the same first letter). Strangely the user **can** delete the first character by highlighting all characters in a variable and then pressing backspace.
https://www.loom.com/share/6f3b65e5684d47568bb8172c2bbe5638

## Possible Solution
Allow all characters to be removed from a variable consistently.

**Comment by irmerk** [comment]
I think https://github.com/accordproject/web-components/issues/73 would be a better approach to this issue, given that the time this would take to implement is not likely to be very short. Plus a user is able to change the complete text, it's just a bit awkward.

**Comment by Michael-Grover** [comment]
@irmerk what if we scrapped having a placeholder text for empty variables, but just made sure that all characters of a variable can be deleted when pressing backspace multiple times to delete every character, like how the user can delete the first character by highlighting all characters in a variable and then pressing backspace?

**Comment by Michael-Grover** [comment]
Unless variable modals are coming soon I think it will be important to address this in some way

**Comment by irmerk** [comment]
I think working on allowing an "empty variable" similar to the highlighting all characters and deleting seems doable.

**Comment by Michael-Grover** [comment]
okay, I updated the issue description to reflect that

**Comment by sanketshevkar** [comment]
Can I work on this issue?
