### ISSUE TITLE
Support Hardbreaks in Markdown

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#153]
# Feature Request 🛍️
Hardbreaks are handled in the [commonmark spec](https://spec.commonmark.org/0.17/#hard-line-breaks), and should be supported in the editor

## Use Case
A user would expect the editor to respect their wishes to maintain extra spaces

## Possible Solution
A toolbar button or hotkey shortcut?

## Context
This should persist:
![image](https://user-images.githubusercontent.com/36460856/87967548-fbfb3d00-ca8c-11ea-8152-59023607274c.png)

Via a `something.md` file which looks like: 
```md
Foo\
\
\
bar
```

**Comment by DianaLease** [comment]
We would also need support for this in https://github.com/accordproject/markdown-transform to be able to roundtrip and persist these line breaks.

**Comment by jeromesimeon** [comment]
The `markdown-transform` supports heartbreaks/linebreaks as far as I can tell:

```
bash-3.2$ more something.md 
Foo\
\
\
bar
bash-3.2$ markus transform --from markdown --to slate --roundtrip --input something.md 
1:55:58 PM - info: 
Foo\
\
\
bar
```

**Comment by DianaLease** [comment]
@jeromesimeon ah, nice!

**Comment by DianaLease** [comment]
I wonder where the issue arises then. I guess when the user creates a line break in the UI it doesn't get added to the slate DOM 🤔

**Comment by jeromesimeon** [comment]
I think we just need to distinguish markdown newlines from hardbreaks? They are different beasts entirely.

```
Foo


bar
```
is two paragraphs

```
Foo\
\
\
bar
```

is one paragraph with line breaks inside it.

**Comment by jeromesimeon** [comment]
Comparison, in GitHub:

<img width="1010" alt="Screenshot 2020-07-20 at 2 04 31 PM" src="https://user-images.githubusercontent.com/670099/87970630-00762480-ca92-11ea-9949-dfdfa3ca6fac.png">

<img width="928" alt="Screenshot 2020-07-20 at 2 04 45 PM" src="https://user-images.githubusercontent.com/670099/87970656-09ff8c80-ca92-11ea-911a-4b2127cd3fe2.png">

**Comment by DianaLease** [comment]
Interesting. I feel like this isn't very intuitive behavior for a rich text editor (Word's behavior being the more intuitive imo). But I guess we would need a specific toolbar option like @irmerk suggested to specifically add a hard break. @Michael-Grover may have a better idea on how to handle this.

**Comment by jeromesimeon** [comment]
> Interesting. I feel like this isn't very intuitive behavior for a rich text editor (Word's behavior being the more intuitive imo). But I guess we would need a specific toolbar option like @irmerk suggested to specifically add a hard break. @Michael-Grover may have a better idea on how to handle this.

Agreed. We are building a rich text editor for markdown though... so unless we change our mind about that I'm not sure what else we can do.

Personally, I think new lines in documents are one of the main source of horrible layout, but that's just taste (and growing up with Don Knuth).

**Comment by jeromesimeon** [comment]
One more thought/question:

What should happen in the UI when you press return? (a new paragraph? a new line/hardbreak/softbreak? both?)

**Comment by Michael-Grover** [comment]
Pressing enter to make a hard break/new paragraph is one of the most consistent behaviors in text editors. I've never seen this functionality need to be an icon in the formatting toolbar since there's a double sized button specifically for it on the keyboard. 

I know I'm stating the obvious and that there are technical limitations, but as a user I would be very confused about why I need to move my mouse to the formatting toolbar to click on a button just to do what I usually can by pressing enter. 

If this was an icon in the formatting toolbar, what would the shortcut be? Can it be enter?

I can think of very legitimate one instance where a user would want a hard break, which is if they want the signature block at the end to be spaced apart from the contract content above.

**Comment by jeromesimeon** [comment]
> Pressing enter to make a hard break/new paragraph is one of the most consistent behaviors in text editors. I've never seen this functionality need to be an icon in the formatting toolbar since there's a double sized button specifically for it on the keyboard.
> 

How do you distinguish between new paragraph and hardbreak?

**Comment by DianaLease** [comment]
Right. I think what Jerome posted here is the core of the issue: https://github.com/accordproject/web-components/issues/153#issuecomment-661245128.
Right now, pressing enter creates a new paragraph, which is entirely different than a hardbreak in markdown.

**Comment by Michael-Grover** [comment]
I'm getting confused with the terminology. I'll stop using hard/soft break + carriage return for now. 

I meant to say that pressing enter should create a new paragraph. Pressing enter multiple times should create empty paragraphs that look like space on the document. Pressing shift+enter should create a new line in the document.

**Comment by Michael-Grover** [comment]
the definitions for hard line break and soft line break I'm finding online are not consistent

**Comment by jeromesimeon** [comment]
> I'm getting confused with the terminology. I'll stop using hard/soft break + carriage return for now.
> 
> I meant to say that pressing enter should create a new paragraph. Pressing enter multiple times should create empty paragraphs that look like space on the document. Pressing shift+enter should create a new line in the document.

🤔 I think that makes sense, trying to separate things:

- I think pressing enter create a new paragraph in the editor right now
- In markdown there is no way to capture this part: create empty paragraphs **that look like space**
- I think it would make sense to use something like shift+enter for hard break

**Comment by irmerk** [comment]
We can only relate ourselves to rich text editors so much, because we are based on markdown which has its own specific specification. So by definition, a user cannot reasonably expect the editor to behave as Word does.

**Comment by Michael-Grover** [comment]
I think a user will expect the editor to behave as Word and Google Docs do, because that's how we are presenting the editor. I think that many people who edit this won't know what Markdown is and won't care. They will just be confused when they try to make space in the document and the editor shows there is space, but then when they exit the document and return, the space is gone without explanation.

original
![image](https://user-images.githubusercontent.com/40569793/87973425-7da39880-ca96-11ea-8d7b-61ef549176c8.png)

Upon leaving document and returning
![image](https://user-images.githubusercontent.com/40569793/87973414-78dee480-ca96-11ea-9779-c633985836df.png)

I wonder if there's some way that we can disable creating two consecutive line breaks, so that the user never creates a document with deliberately consecutive line breaks, then is disappointed to see that the line breaks have disappeared for no apparent reason.

**Comment by irmerk** [comment]
I don't think that's the right approach. The onus is on us to help present the editor in a way which is understandable, because we are using markdown. Not HTML, not plain text. We're tied to markdown and need to adapt to that rather than trying to hack the markdown format to fit a completely different application.

**Comment by jeromesimeon** [comment]
> I think a user will expect the editor to behave as Word and Google Docs do, because that's how we are presenting the editor.

I'm a bit curious about that. Is it really how we present it?

**Comment by Michael-Grover** [comment]
we have to manage a user's expectation that they will not be able to create space the same way they can in the normal text editors that people who work with contracts use, like Word and Google Docs. We can't assume our users know what markdown is and what the limitations of markdown are. I'm kind of warming up to having a "vertical spacer" option in the formatting toolbar as was previously suggested.

I think that we definitely should not let users create multiple consecutive line breaks in the editor if the spaces will just disappear the next time they load the editor. Or we could have some warning like this:

![image](https://user-images.githubusercontent.com/40569793/87974542-37e7cf80-ca98-11ea-9c47-6a646e84d294.png)

Can we talk about this on tomorrow's call?

**Comment by jeromesimeon** [comment]
> we have to manage a user's expectation that they will not be able to create space the same way they can in the normal text editors that people who work with contracts use, like Word and Google Docs. We can't assume our users know what markdown is and what the limitations of markdown are. I'm kind of warming up to having a "vertical spacer" option in the formatting toolbar as was previously suggested.
> 
> I think that we definitely should not let users create multiple consecutive line breaks in the editor if the spaces will just disappear the next time they load the editor. Or we could have some warning like this:
> 
> ![image](https://user-images.githubusercontent.com/40569793/87974542-37e7cf80-ca98-11ea-9c47-6a646e84d294.png)
> 
> Can we talk about this on tomorrow's call?

This is certainly an interesting (and I agree important) discussion! We do have to manage expectations. I would probably just note that re building google docs or MS word is way beyond or scope (or resources). The MSWord add in might be a better option down the road for people who want an experience like MS word.

I don't really know how to handle users expectations for the markdown editor, but sure would be happy to discuss and help if I can.

**Comment by jeromesimeon** [comment]
For reference

![MarkdownNewLines](https://user-images.githubusercontent.com/670099/87977361-9fa01980-ca9c-11ea-853e-860665ea6c54.gif)

**Comment by irmerk** [comment]
@jeromesimeon this reminds me of how a lot of apps seem to be moving towards supporting `/` for commands to cut down on toolbar real estate (Slab has grayed text on new lines "_Type / for Commands_"). This is not a Word or GDocs standard. Perhaps this can act as inspiration for solving this.

**Comment by jeromesimeon** [comment]
> @jeromesimeon this reminds me of how a lot of apps seem to be moving towards supporting `/` for commands to cut down on toolbar real estate and improve a11y (Slab has grayed text on new lines "_Type / for Commands_", Slack supports this as a command, Notion...). This is not a Word or GDocs standard. Perhaps this can act as inspiration for solving this.

That's interesting. I can't say I 100% follow your idea, but it makes me think of inline-replacement / escape sequences. e.g., in Slack you write `- something` and it automatically turns it into a rich-text bullet. Is that the kind of thing you're thinking about?

Might be a bit more ambitious than simply solving the specific issue of line breaks but that could be an interesting direction.

**Comment by martinhalford** [comment]
My 2 cents worth...

It might be good to distinguish between the implementation of whitespace in Markdown and how whitespace is permitted/handled in the Editor.

From a Markdown perspective, it would be nice if the specification of CiceroMark supported new lines/whitespace for systems that don't necessarily use the Editor.  This is mainly for stylistic reason (e.g. new lines for signatures) but useful when rendering drafts.

**Comment by jeromesimeon** [comment]
> My 2 cents worth...
> 
> It might be good to distinguish between the implementation of whitespace in Markdown and how whitespace is permitted/handled in the Editor.
> 
> From a Markdown perspective, it would be nice if the specification of CiceroMark supported new lines/whitespace for systems that don't necessarily use the Editor. This is mainly for stylistic reason (e.g. new lines for signatures) but useful when rendering drafts.

Couple of points/questions:
1. We are limited by what we can save in markdown (for better or worse, since we haven't picked an XML format like Word did -- XML has notions of significant / insignificant whitespace)
2. Would the notion of markdown hard line break be sufficient to capture the use case you describe in your second paragraph?

**Comment by irmerk** [comment]
As noted in the call, I think having an arbitrary node or block, similar to the smart clause template, be supported in the editor may help solve this. That is, at least for a signature block and the requirement of enough space to fit a signature.

**Comment by jeromesimeon** [comment]
> As noted in the call, I think having an arbitrary node or block, similar to the smart clause template, be supported in the editor may help solve this. That is, at least for a signature block and the requirement of enough space to fit a signature.

For me, there is something technically appealing there :) but I don't trust my non-UX-designer judgment at all on this.

**Comment by martinhalford** [comment]
> 2. Would the notion of markdown hard line break be sufficient to capture the use case you describe in your second paragraph?

@jeromesimeon  Yes - something involving a backslash `\` or double-space at the end of a line `  ` is all that would be needed.

**Comment by irmerk** [comment]
To reiterate the point I finished on in the call: 

This is _new tech_, and we should not hamstring it by trying to force it to fit the model of the past (Word, Docs, [XML](https://github.com/accordproject/web-components/issues/153#issuecomment-662699845), [PDF](https://github.com/accordproject/cicero/issues/562)). There won't be a way out of having a learning curve, but we just need to minimize the curve with thoughtful assistance.

I think updating to markdown for the benefit of consistency and ability to machine-read becomes more useless the more we try to force it into taking the same shape as pre-markdown.

**Comment by dselman** [comment]
Editor support for SHIFT-ENTER to insert a markdown linebreak (`<br/>` in HTML) has been added. Closing this - please create new issues if this is insufficient with additional details.
