### ISSUE TITLE
Possible to drag and drop a clause template into a list

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#157]
# Bug Report 🐛
It's possible to drag and drop a clause template into a bulleted list or numbered list

## Expected Behavior
when dragging a clause template into a list, the clause template should be placed outside of the list rather than becoming part of the list

## Current Behavior
When a user drags a clause template onto a bulleted list or numbered list, the clause template appears to become the first element of the list, with a bullet in front of it.

![image](https://user-images.githubusercontent.com/40569793/88322569-e5542080-ccee-11ea-9157-5c31d1956672.png)
![image](https://user-images.githubusercontent.com/40569793/88322745-29472580-ccef-11ea-8a96-96f17f8671ce.png)

video
https://www.loom.com/share/4b53763bf2544879854bc2ac3da63eea

**Comment by sanketshevkar** [comment]
Hey is this bug solved? I'll like to work on this issue.

**Comment by Michael-Grover** [comment]
@sanketshevkar it looks like this bug hasn't been solved. I've assigned it to you. Thanks for volunteering! I am not an engineer, so if you have any questions about this bug, they should be directed towards @DianaLease, @irmerk, or another code maintainer.

**Comment by sanketshevkar** [comment]
@Michael-Grover Okay sure.

**Comment by sanketshevkar** [comment]
@Michael-Grover is there any use case wherein you'll be needing a list of clauses?

**Comment by Michael-Grover** [comment]
@sahalsaad No, I don't think so. @jeromesimeon could probably answer that question more accurately. He is busy today, but may be able to respond tomorrow.

**Comment by sanketshevkar** [comment]
@Michael-Grover I've added a pull request for this issue. I've added both behaviours, adding clause inside as well as outside a list.
