### ISSUE TITLE
Changing a group of paragraphs to a numbered list only indents the paragraphs

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#158]
# Bug Report 🐛
If the user highlights a group of paragraphs and clicks the numbered or bulleted list icons, the paragraphs are indented, but not given a bullet or a number.

![image](https://user-images.githubusercontent.com/40569793/88326510-1daa2d80-ccf4-11ea-8fb1-82c81f559f34.png)

## Expected Behavior
Highlighting a group of paragraphs and clicking the numbered or bulleted list icons should turn the highlighted text into a numbered or bulleted list

video:
https://www.loom.com/share/64f31fb19dd346ab971859ff2a28a0dc

**Comment by gatij10** [comment]
Is this issue still open? May I solve the bug ?

**Comment by Michael-Grover** [comment]
@gatij10 I checked and it looks like this bug still exists. Thanks for volunteering, I've assigned this issue to you.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
The issue seemed inactive so I did some experiments on it and deduced the following things from it:
1. Selection of multiple paragraphs from top to bottom causes no bug.
2. Selection of multiple paragraphs from bottom to top causes bugs.

Selected from the top
![Screenshot from 2021-02-20 19-25-04](https://user-images.githubusercontent.com/59891164/108597940-99b34380-73b1-11eb-9878-817e70a645e0.png)
Working as expected.
![Screenshot from 2021-02-20 19-25-28](https://user-images.githubusercontent.com/59891164/108597943-9cae3400-73b1-11eb-8453-344055ff1df8.png)
Selecting from bottom
![Screenshot from 2021-02-20 19-25-55](https://user-images.githubusercontent.com/59891164/108597946-9e77f780-73b1-11eb-96c7-6026ea85bfed.png)
The bug and console.logs() depicting that.
![Screenshot from 2021-02-20 19-26-21](https://user-images.githubusercontent.com/59891164/108597950-a0da5180-73b1-11eb-84be-cb9620778259.png)

It seems from the above experiments that the 2nd elements of focus and anchor are not being properly understood by the selection, which may be the cause for the above bug.

**Comment by dselman** [comment]
Nice analysis. I suggest you look at the code inside isList:

https://github.com/accordproject/web-components/blob/master/packages/ui-markdown-editor/src/utilities/toolbarHelpers.js

**Comment by K-Kumar-01** [comment]
> Nice analysis. I suggest you look at the code inside isList:
> 
> https://github.com/accordproject/web-components/blob/master/packages/ui-markdown-editor/src/utilities/toolbarHelpers.js

@dselman 
The console.logs() were made by changing the code inside the above-mentioned link.
As far as I can understand, this seems to be an issue of `slate` itself, though I am not sure about this.

**Comment by gatij10** [comment]
> > Nice analysis. I suggest you look at the code inside isList:
> > https://github.com/accordproject/web-components/blob/master/packages/ui-markdown-editor/src/utilities/toolbarHelpers.js
> 
> @dselman
> The console.logs() were made by changing the code inside the above-mentioned link.
> As far as I can understand, this seems to be an issue of `slate` itself, though I am not sure about this.

I observed that on selecting from bottom, initially the offset values of anchor and focus are swapped.
![Screenshot 2021-02-20 202333](https://user-images.githubusercontent.com/54245799/108599847-90c67000-73b9-11eb-9c41-7f361309a0d8.png)

**Comment by K-Kumar-01** [comment]
@dselman @Michael-Grover 
I had opened a pull request. Let me know if there are any changes required.

**Comment by irmerk** [comment]
@K-Kumar-01 and @gatij10 I think it makes sense to resolve which PR you two want to use.

**Comment by K-Kumar-01** [comment]
@gatij10 
There was already a PR made by me. So I request you to please close your PR

**Comment by gatij10** [comment]
@K-Kumar-01 Your PR failed in the netlify build, that's why I created a new PR.

**Comment by K-Kumar-01** [comment]
@gatij10
That is fixable. I would request you to please close down your PR.

**Comment by gatij10** [comment]
okay

**Comment by K-Kumar-01** [comment]
> okay

Thank you
