### ISSUE TITLE
Should formulas be styled in a way that does not suggest they can be edited 

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/web-components#177]
# Discussion 🗣
During a demo of the template formulas (e.g., fixed interest monthly payment for a loan calculated in Ergo) in the contract editor, the user got confused thinking they could click inside the box to change the value.

Would there be a way to style formulas in a way that does not suggest they can be edited (something else than a box, or a solid box or something else?) while still drawing attention to them as being calculated text in the contract?

<img width="645" alt="Screenshot 2020-08-26 at 1 34 18 PM" src="https://user-images.githubusercontent.com/670099/91337166-f6d29180-e7a0-11ea-8915-2a6c49fc9fc2.png">

(The different color also wasn't very easy to distinguish during the demo through video conferencing).

**Comment by DianaLease** [comment]
closed by #180
