### ISSUE TITLE
Add a React DOM Testing Framework

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/web-components#192]
# Feature Request 🛍️

Currently, the web-components library does not have any standardized way of unit testing the React components in this repo. The first step to solving this problem should be to install and configure a test framework with a sample test to allow other contributors to add further tests. 

## Possible Solution
I propose `React Testing Library` as it is now the most popular DOM testing library for React and handles hooks well. https://testing-library.com/docs/react-testing-library/intro

**Comment by Ian-Yy** [comment]
Hi, may I pick this up? So, I will try to implement `React Testing Library` and write some sample tests right?

**Comment by irmerk** [comment]
Yes @Ian-Yy that sounds good!

**Comment by Ian-Yy** [comment]
Hi, I've went through both `React Testing Library` and this repo. Now, I am confused whether should I be writing sample test for the packages or for the repo. Because I see components in packages is another repo and some even have their own unit tests.

**Comment by irmerk** [comment]
@Ian-Yy I think start with writing a test for for a package and we can expand from there. So maybe start with [`ui-markdown-editor`](https://github.com/accordproject/web-components/tree/master/packages/ui-markdown-editor) and don't focus as much on the entire repo - we can iterate from here and move on to the rest of the packages.

**Comment by Ian-Yy** [comment]
Hi @irmerk , I've created a PR. please review and let me know if its ok. Thanks
