### ISSUE TITLE
Terminal showing error "lerna: command not found" even after installing lerna with "npm install -g lerna"

### ISSUE THREAD

**Issue by surajkulriya** [accordproject/web-components#203]
#112 Bug Report 🐛
Terminal showing "lerna: command not found" even after installing it

When installing lerna in ubuntu 18.04 with command "npm install -g lerna" it successfully gets installed but when we run any new command related to lerna like "lerna --version" or "lerna clean" it shows "lerna: command not found"

And after installing once when you again use the installing command it should return something like "lerna already installed 0 pacakages upgraded 0 new installed......" but it reinstalls it completely again.
## Expected Behavior

It should execute the command with no errors.
## Current Behavior

It shows "lerna: command not found"

### Desktop
 - OS: ubuntu 18.04
 - Browser: Chrome

**Comment by jeromesimeon** [comment]
> #112 Bug Report 🐛
> Terminal showing "lerna: command not found" even after installing it
> 
> When installing lerna in ubuntu 18.04 with command "npm install -g lerna" it successfully gets installed but when we run any new command related to lerna like "lerna --version" or "lerna clean" it shows "lerna: command not found"
> 
> And after installing once when you again use the installing command it should return something like "lerna already installed 0 pacakages upgraded 0 new installed......" but it reinstalls it completely again.
> 
> ## Expected Behavior
> It should execute the command with no errors.
> 
> ## Current Behavior
> It shows "lerna: command not found"
> 
> ### Desktop
> * OS: ubuntu 18.04
> * Browser: Chrome

This is most likely not related to this repo, but a lerna installation issue. I would suggest to look into help from the lerna community for this.

Possibly if on Windows this thread might help: https://github.com/lerna/lerna/issues/387

**Comment by dselman** [comment]
If you cannot install lerna on Ubuntu 18.04, I'm afraid you will have to file an issue on their repo: 
https://github.com/lerna/lerna/issues
