### ISSUE TITLE
Not receiving invitation link on Gmail from slack

### ISSUE THREAD

**Issue by surajkulriya** [accordproject/web-components#204]
# Bug Report 🐛
After entering my gmail id in slack channel invitation column it says "Success! Check 'surajkulriya@gmail.com' for an invite from Slack." but I did not received any email regarding that.

### Desktop
 - OS:  18.04
 - Browser: Chrome

**Comment by jeromesimeon** [comment]
> # Bug Report 🐛
> After entering my gmail id in slack channel invitation column it says "Success! Check '[surajkulriya@gmail.com](mailto:surajkulriya@gmail.com)' for an invite from Slack." but I did not received any email regarding that.
> 
> ### Desktop
> * OS:  18.04
> * Browser: Chrome

Hi @surajkulriya Thanks for the report! I'm looking into this. For the time being you should be able to sign up with this direct link. https://accord-project.slack.com/join/shared_invite/zt-hej4q3ps-I1G2uSfKUhDMvcFKRggXGw#/

Let me know if that works.

**Comment by surajkulriya** [comment]
> > # Bug Report bug
> > After entering my gmail id in slack channel invitation column it says "Success! Check '[surajkulriya@gmail.com](mailto:surajkulriya@gmail.com)' for an invite from Slack." but I did not received any email regarding that.
> > ### Desktop
> > 
> > * OS:  18.04
> > * Browser: Chrome
> 
> Hi @surajkulriya Thanks for the report! I'm looking into this. For the time being you should be able to sign up with this direct link. https://accord-project.slack.com/join/shared_invite/zt-hej4q3ps-I1G2uSfKUhDMvcFKRggXGw#/
> 
> Let me know if that works.

Thank you sir the link you provided me is working and I have joined the channel.
