### ISSUE TITLE
Remove hyperlink modal fade-in effect

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#218]
# Discussion 🗣
Currently when a user opens the hyperlink modal by clicking on the icon or using the shortcut, the modal slowly fades in. Let's remove this animation, it's not necessary and makes the editor feel sluggish.

**Comment by irmerk** [comment]
Agreed.

**Comment by Prateeknandle** [comment]
I would like to do it , plz assign me.

**Comment by K-Kumar-01** [comment]
@irmerk  @Michael-Grover 
The issue seems inactive. I would like to work on it.

**Comment by Michael-Grover** [comment]
@K-Kumar-01 thanks, I've just assigned it to you

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I have made a PR which will be able to close the issue.
Let me know if any changes are required :)
