### ISSUE TITLE
Deprecated import usage uuid

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/web-components#224]
# Discussion 🗣

We are using the uuidv4 from the 'uuid' package. This is deprecated.

## Context

Attaching a Screenshot
![DeepinScreenshot_20201215164344](https://user-images.githubusercontent.com/59891164/102213967-8f7e5000-3efd-11eb-8efd-3cb787995a34.png)
In console.log() it can be seen the package is deprecated

## Detailed Description

Should use v4() module instead of this package. 

**Would you like to work on the issue**
Yes

**Comment by irmerk** [comment]
I agree we should switch to [uuid](https://www.npmjs.com/package/uuid), as noted in [uuidv4's documentation](https://github.com/thenativeweb/uuidv4#please-note).

**Comment by K-Kumar-01** [comment]
@irmerk 
I have created a PR for the issue. Let me know if any changes are required :)
