### ISSUE TITLE
Unnecessary Imports

### ISSUE THREAD

**Issue by K-Kumar-01** [accordproject/web-components#230]
# Discussion 🗣

There are some files present in the codebase that have unnecessary imports.
These could be removed as they are not used.

## Detailed Description

Particularly, I saw three such files (might have missed some). 
They are:
1.`4-ContractEditor.stories.js`
2.`3-ConcertoForm.stories.js`
3.`FormattingToolbar/index.js`

**Comment by irmerk** [comment]
What are the imports that are unnecessary? Could you like to the code?

**Comment by K-Kumar-01** [comment]
> What are the imports that are unnecessary? Could you like to the code?

@irmerk 
These were the lines where imports are not being used.

### FormattingToolbar/index.js
**_Line 4:_**`import { Transforms } from 'slate';`

### 4-ContractEditor.stories.js
_**Line 4:**_: `import { Provider, connect } from 'react-redux';`  (connect)
_**Line 15 **_: 
`import { text, select, boolean, object } from '@storybook/addon-knobs';` (text, object)
_**Line 16:**_
`import { storiesOf } from '@storybook/react'`
_**Line 18:**_
`import { Editor, Node, Transforms } from 'slate';` (Node)

### 3-ConcertoForm.stories.js
**_Line 1:_**`import React, { useState } from 'react';` (useState)

**Comment by irmerk** [comment]
I think removing the unused imports works. However, this is pretty low priority, especially for the `...stories.js` files because they are not published to `npm`.

**Comment by K-Kumar-01** [comment]
> I think removing the unused imports works. However, this is pretty low priority, especially for the `...stories.js` files because they are not published to `npm`.

Well, I had no idea about the priority of the packages :sweat_smile:. I think we can close the issue then as it hardly affects the work
