### ISSUE TITLE
Migrate CI/CD to GitHub Actions

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/web-components#235]
Motivated by the recent Technical Steering Committee discussion about reducing the number of vendors and the notes from @jeromesimeon https://github.com/accordproject/technical-steering-committee/issues/4#issuecomment-763173151
I propose that this repo is migrated to use GitHub Actions.

# Chore 🧼
The new pipeline should include the following phases and be feature equivalent to the existing Travis based workflows.
- Build (using existing `lerna` scripts)
- Test (using existing unit test scripts)
- Publish to NPM
- Deploy to Netlify (for hosting `storybook`)

**Comment by igarg2001** [comment]
Can I work on this?

**Comment by irmerk** [comment]
Hi @igarg2001, apologies I didn't mark it, but I already started working on this! This work is needed in most of our other repos, though, see https://github.com/accordproject/technical-steering-committee/issues/4#issuecomment-763173151

**Comment by jeromesimeon** [comment]
Those CI/CD items are better handled by maintainers. (need a good understanding of the deployment process, testing,  sometimes org access, etc.)

**Comment by igarg2001** [comment]
No issues, I'll look for some other issues.

**Comment by mttrbrts** [comment]
@rkotangoor. Tagging you so that I can assign it to you...

**Comment by rkotangoor** [comment]
> @rkotangoor. Please reply to this thread so that I can assign it to you

@mttrbrts , can I have this assigned to me. Thank you.
