### ISSUE TITLE
Add repository information to package.json

### ISSUE THREAD

**Issue by steelbrain** [accordproject/web-components#238]
# Feature Request 🛍️

Add repository information to package.json

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository

## Use Case

It'll point people discovering your packages on NPM to your Github repository

**Comment by irmerk** [comment]
Good suggestion! I think we can do a coordinated addition to all our main repositories at the same time so we don't overlook any. I opened this within the `techdocs` repository as a sort of central hub. 

I'm going to close this one in favor of https://github.com/accordproject/techdocs/issues/341
