### ISSUE TITLE
Not allowing cursor caret in non-editable clause text

### ISSUE THREAD

**Issue by sanketshevkar** [accordproject/web-components#248]
# Feature Request 🛍️

## Use Case

When cursor caret is blinking inside the non-editable clause text, it feels as if that text is editable. Since the text is read-only, cursor caret should not be allowed to place inside the clause text.

## Possible Solution

Set `caret-color: transparent;` for read-only text.

**Comment by irmerk** [comment]
Closed due to discussion in #249 

Useful to discuss possible solutions before trying to implement.
