### ISSUE TITLE
Lerna install permissions issue on Ubuntu 20.0x

### ISSUE THREAD

**Issue by hemant767** [accordproject/web-components#256]
When I used to run it locally in my ubuntu system it was giving me error.
# Bug Report 🐛

## Expected Behavior
Following the steps in the read me to run locally ,it should have run fine .
## Current Behavior
But now it's giving error in the ubuntu system.
## Possible Solution
In the steps to run it locally ,we should include one more step .We should first initialise lerna by lerna init.

## Steps to Reproduce

1.sudo npm install -g lerna
2.lerna init
3.lerna clean && lerna bootstrap && lerna run build
4.cd packages/storybook
5.npm run storybook

## Context (Environment)
I was trying to run it locally on my ubuntu system version 20.04

## Detailed Description
I am just adding another step to initialise lerna by lerna  #init.
![Screenshot from 2021-02-22 20-42-15](https://user-images.githubusercontent.com/62658209/108803810-9c848300-75c1-11eb-9489-bafb303cd1f4.png)

## Possible Implementation
We should first initialise lerna by lerna init in the first step
The it will run fine.

**Comment by hemant767** [comment]
> When I used to run it locally in my ubuntu system it was giving me error.
> 
> # Bug Report 
> ## Expected Behavior
> Following the steps in the read me to run locally ,it should have run fine .
> 
> ## Current Behavior
> But now it's giving error in the ubuntu system.
> 
> ## Possible Solution
> In the steps to run it locally ,we should include one more step .We should first initialise lerna by lerna init.
> 
> ## Steps to Reproduce
> 1.sudo npm install -g lerna
> 2.lerna init
> 3.lerna clean && lerna bootstrap && lerna run build
> 4.cd packages/storybook
> 5.npm run storybook
> 
> ## Context (Environment)
> I was trying to run it locally on my ubuntu system version 20.04
> 
> ## Detailed Description
> I am just adding another step to initialise lerna by lerna #init.
> ![Screenshot from 2021-02-22 20-42-15](https://user-images.githubusercontent.com/62658209/108803810-9c848300-75c1-11eb-9489-bafb303cd1f4.png)
> 
> ## Possible Implementation
> We should first initialise lerna by lerna init in the first step
> The it will run fine.

[``](

- [ ] ### url

)

**Comment by dselman** [comment]
I don't understand why `lerna init` would have anything to do with OS permissions; it is usually used to create a new lerna monorepo.
https://github.com/lerna/lerna/tree/main/commands/init#readme

Are you sure that installing lerna using sudo was not enough to fix your permissions issue?

**Comment by hemant767** [comment]
No ,whenever I run it without initialising lerna on ubuntu (as I don't use windows),I get error .To confirm this I ran this repo about 3 times without initialisng which in result given error but after initialising lerna It works fine.

**Comment by dselman** [comment]
Can you please run 'lerna --version' before and after you run 'lerna init'?

Also does package.json get modified?

**Comment by hemant767** [comment]
Actually sudo fixed my permission issue but without lerna init it didn't work.And version and package.json remains same .Why version of lerna and package.json  would  change after and before initialising lerna ?It's obvious that it will remain same.

**Comment by hemant767** [comment]
I am sorry but now , i didn't use lerna init and it ran fine.
