### ISSUE TITLE
Soft Break not Working => Line Break and Soft Break are interchanged in the code

### ISSUE THREAD

**Issue by d-e-v-esh** [accordproject/web-components#267]
# Bug Report 🐛

The soft brake was confused with the line break (i.e. hard break) in the code
This was also causing issue #263 
There was no actual functional ``linebrake``, just a ``headingbrake`` with a restriction on the paragraph so it doesn't mess up anything when called from a paragraph. For this reason, the soft break was not working. 

You can see this when you open up the demo and it appears like this:

![chrome_RQFT8jGi0h](https://user-images.githubusercontent.com/59534570/109197977-aa095b00-77c3-11eb-82ab-5f3acb059cbf.png)

Every single break we created came under type ``headingbreak`` even if it was created in a paragraph.

As we can see the soft break is not working in its place and has instead taken up the place of the hard break.

## Expected Behavior

It should appear like this:

![chrome_EX6SKZBtq3](https://user-images.githubusercontent.com/59534570/109198212-f6549b00-77c3-11eb-8f84-b1ecaa2e1d09.png)

## Current Behavior

![chrome_RQFT8jGi0h](https://user-images.githubusercontent.com/59534570/109197977-aa095b00-77c3-11eb-82ab-5f3acb059cbf.png)

## Possible Solution

I have fixed up the code and will create a pull request soon explaining the solution in detail

## Steps to Reproduce

1. Go to the demo page and the problem will appear under the break section

### Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version 88.0.4324.182 (Official Build) (64-bit)

## Possible Implementation

1. My solution is to rename the ``headingbreak`` to ``linebreak`` and ``linebreak`` to ``softbreak`` so that it automatically matches the template of the frontpage. This shows that this is how it was intended to be written.
2. Create a new insertHeadingBreak function and implemented it in a way that it will only get called when we press ``Enter`` from a heading block.
3. By doing this, every single normal break will have a type of ``linebreak``.

**Comment by dselman** [comment]
I think the terminology here may be causing confusion.

**Softbreaks** in the markdown specification are typically rendered as spaces in HTML: 
6.10 Soft line breaks https://spec.commonmark.org/0.29/

Pressing ENTER in the editor should create a new paragraph.

Pressing SHIFT-ENTER (sometimes called a soft break in editors!) should create a newline. The markdown specification calls this a hard line break (section 6.9).

**Comment by d-e-v-esh** [comment]
@dselman That is true, the terminology is definitely a little confusing.

**Comment by Pratik1234agarwal** [comment]
I am new here. Wanted to work on this issue. Can I get started ?

**Comment by irmerk** [comment]
@Pratik1234agarwal feel free to share here what you'd like to do in regards to this issue that is not captured in #270.

**Comment by irmerk** [comment]
I _believe_, based on the tech working group call tonight, this is not actually an Issue. Rather, just a confusion on terminology. Correct @jeromesimeon and @d-e-v-esh?

**Comment by jeromesimeon** [comment]
> I _believe_, based on the tech working group call tonight, this is not actually an Issue. Rather, just a confusion on terminology. Correct @jeromesimeon and @d-e-v-esh?

That's what I understood for the demo and discussion as well.

We should certainly clarify the terminology and how WYSIWYG editing relates to the underlying commonmark. Maybe staying away from "soft break" and "hard break" altogether when we talk about the editing experience would actually improve things.

e.g., `linebreak` (represented as a commonmark hard break) and `paragraph break`

**Comment by d-e-v-esh** [comment]
@irmerk  @jeromesimeon  That is true. This is very confusing. I didn't think of it then but now it makes more sense. We should only have one break (linebreak). right? We can discuss a little bit more on how we want to trigger the line break.
The line break could be added with a shift + enter and the normal break would be plain enter. That is right?

**Comment by jeromesimeon** [comment]
> @irmerk @jeromesimeon That is true. This is very confusing. I didn't think of it then but now it makes more sense. We should only have one break (linebreak). right? We can discuss a little bit more on how we want to trigger the line break.
> The line break could be added with a shift + enter and the normal break would be plain enter. That is right?
> But then we need to remove that (soft break) sample text from the markdown editor. I think that was the one that caused the problem

I think this makes a lot of sense. I'm unclear that the distinction between commonmark softbreak and hardbreaks makes much sense from a user of the rich text editor. And if someone really needs that distinction we can revisit that decision at a later date.

I think that also means simply: remove those examples from the demo!

**Comment by d-e-v-esh** [comment]
@jeromesimeon @irmerk  Yes, so I thought about this for a few minutes now. The thing that I wasn't able to convey in the call was that I didn't actually change the functionality of any breaks. This is how it was actually supposed to be after removing the restriction on the enter key. I just matched the function name in code from what was written in the examples from the demo text. We can put appropriate naming on them now and not care about the soft and hard breaks. This confusion was caused by the text in the demo. That needs to be changed.

**Comment by irmerk** [comment]
Yes agreed.

I think in `ui-markdown-editor`, we should have:
- **Page break**: [CommonMark leaf block thematic break](https://spec.commonmark.org/0.29/#thematic-breaks)
- **Line break**: [CommonMark inline hard line break](https://spec.commonmark.org/0.29/#hard-line-breaks)
- **Paragraph break**: [CommonMark leaf block paragraph](https://spec.commonmark.org/0.29/#paragraphs)
- **Heading**: [CommonMark leaf block ATX heading](https://spec.commonmark.org/0.29/#atx-headings)

Support for [CommonMark inline soft line break](https://spec.commonmark.org/0.29/#soft-line-breaks) is _supported_, but we don't emphasize it in the editor (or the demo text in the Storybook).
