### ISSUE TITLE
Paragraph styling options obscured by Clause Template

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#278]
# Bug Report 🐛
Paragraph styling options are obscured by Clause Template
![image](https://user-images.githubusercontent.com/40569793/109998645-70fb4a00-7cdf-11eb-9368-2f1cbdff66b4.png)

## Expected Behavior
the paragraph styling options dropdown should be in front of all content so that users can choose their styling option.

## Possible Solution
Change the Z-index of some elements of the UI

## Steps to Reproduce
1. go to the [contract editor in Netlify](https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor)
2. Hover over "normal" on the left side of the formatting toolbar
3. See that the dropdown is covered by the clause template
![image](https://user-images.githubusercontent.com/40569793/109999026-cf282d00-7cdf-11eb-80b6-4d08b311ae8a.png)

## Context (Environment)
Mac OS, Chrome

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I would like to work on this issue

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I am unable to reproduce the issue. I am on Linux and google chrome. It seems to be working fine here.
![Screenshot from 2021-03-05 15-46-13](https://user-images.githubusercontent.com/59891164/110101728-f4916580-7dc9-11eb-9796-7c3da2abb4d0.png)

**Comment by Michael-Grover** [comment]
@K-Kumar-01 interesting. I just confirmed and was able to reproduce the bug on my computer (Macbook pro, Big Sur, Chrome)

@irmerk @dselman @DianaLease  are you able to reproduce this?

**Comment by Michael-Grover** [comment]
@rkotangoor test

**Comment by d-e-v-esh** [comment]
@Michael-Grover I am able to reproduce this bug. Should I look into it?
![crop prob](https://user-images.githubusercontent.com/59534570/110229754-b8791480-7f31-11eb-89ab-0722990931be.png)

**Comment by K-Kumar-01** [comment]
@d-e-v-esh 
Could you please tell the system and platform you ate working on?

**Comment by d-e-v-esh** [comment]
@K-Kumar-01 Actually now when I look at it. I can't reproduce it locally either. It only occurs in the Storybook demo online.

**Comment by Michael-Grover** [comment]
@d-e-v-esh thanks, I've assigned it to you 👍

**Comment by Cronus1007** [comment]
@d-e-v-esh Shall I look into this issue .

**Comment by naveen8801** [comment]
Hii @Michael-Grover  ,  can i work on it ?

**Comment by naveen8801** [comment]
@d-e-v-esh  , are you working on it ? ,

**Comment by d-e-v-esh** [comment]
@naveen8801 No, you already created a PR right.

**Comment by naveen8801** [comment]
@d-e-v-esh  , i have deleted previous one , because there was some issue in rest of UI while changing styles of Clause component . if you wanna work you can take your time , i can suggest you some changes which can be helpful :-)

**Comment by d-e-v-esh** [comment]
@naveen8801 did you record what was going wrong? I'll work on this one next then and see if I can fix this.

**Comment by naveen8801** [comment]
@d-e-v-esh  , after changing z-index , while hovering over slate in Contract editor  , some icons such as edit , delete , dragger etc. were not visible . so there will be some other way of fixing this ,

**Comment by d-e-v-esh** [comment]
@naveen8801 Ok... I'll take a look at that tomorrow

**Comment by K-Kumar-01** [comment]
@d-e-v-esh
Are you going to work on this as I am also able to reproduce the issue now. Also, I have found a solution for this

**Comment by K-Kumar-01** [comment]
@d-e-v-esh 
Are you going to work on the issue, as I am also able to reproduce it now

**Comment by d-e-v-esh** [comment]
Ya, I'll work on this.
