### ISSUE TITLE
Discuss how many heading options should be in the markdown editor and contract editor

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#280]
In the markdown editor UI, users can currently choose three heading styles (H1, H2, H3), however markdown allows for 6 heading styles. The team needs to decide whether this many styles is necessary for editing contracts. I suggest discussing the topic at the Technology Working Group Call on March 10th so that we can have the input of engineers and lawyers.

## Context
The issue was discussed a bit here:
https://github.com/accordproject/web-components/issues/276

**Comment by jeromesimeon** [comment]
For reference:

CommonMark: 6 https://spec.commonmark.org/0.29/#atx-heading

https://templatemark-dingus.netlify.app/#md3=%7B%22source%22%3A%22%23%20one%5Cn%23%23%20two%5Cn%23%23%23%20three%5Cn%23%23%23%23%20four%5Cn%23%23%23%23%23%20five%5Cn%23%23%23%23%23%23%20six%5Cn%23%23%23%23%23%23%23%20seven%5Cn%22%2C%22defaults%22%3A%7B%22templateMark%22%3Atrue%2C%22ciceroMark%22%3Afalse%2C%22html%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

HTML: 6 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

Google Docs: 3

MS Word: 9

**Comment by Michael-Grover** [comment]
Based on the tech WG call on March 10, it's my understanding that we are including all 6 headers in the style dropdown, and leaving it up to the consumer of the component how they want to style those headers.

**Comment by d-e-v-esh** [comment]
@Michael-Grover Should I start to work on including them in the main dropdown list? Should the `H1`, `H2`, and `H3` get bigger in size?

**Comment by Michael-Grover** [comment]
@d-e-v-esh yes, let's make
h1 = 25px (stays the same)
h2 = 25px (keep h2 left aligned to differentiate from H1)
h3 = 20px
h4 = 18px
h5 = 16px
h6 = 14px (same size as normal paragraph), but make the font and color the same as what we use for the page break text. H6 should be all capital letters:
![image](https://user-images.githubusercontent.com/40569793/110824137-c516a900-8260-11eb-9ba8-a5a0457bcc8b.png)

**Comment by Michael-Grover** [comment]
@d-e-v-esh let me know if you'd like me to create an issue for this. Feel free to create an issue or PR. If you create an issue, @ me and I'll assign it to you.
