### ISSUE TITLE
Document Javascript Coding Guidelines

### ISSUE THREAD

**Issue by Cronus1007** [accordproject/web-components#286]
# Problem Description 🗣

1. Lack of Javascript Coding Guidelines

 - reduces efficiency of communication and pull requests
 - sets new contributors up to fail
 - increases cognitive work of working across multiple repositories
2. Lack of .editorconfig and browserlist
3. Lack of proper test Cases (in the main directory)
-  Laying down a `test` folder consisting of both `e2e` and `unit`
4. Moving from `stylelint` to `prettier`.
  - Prettier not only integrates itself not only with `css` but also with `less,graphql,js,ts,yaml` etc.
  - Stylelint integrates itself with `styleint` and `jsfiddle`.
5. Setting up `dependabot` to keep a track of the latest version of the dependencies.

**Comment by Cronus1007** [comment]
@irmerk These are seperate issues. This issue has to be implemented into several bits and can make the repository code much organized and maintainable.

**Comment by irmerk** [comment]
I think it would be great to create individual Issues for each of these then. It looks like 1, 2, 4, 5, and 6 should be in [the TSC](https://github.com/accordproject/technical-steering-committee/).

**Comment by Cronus1007** [comment]
@irmerk Shall I close this issue now since they have been discussed in [the TSC.](https://github.com/accordproject/technical-steering-committee/)
