### ISSUE TITLE
Better editor for linked data

### ISSUE THREAD

**Issue by dselman** [accordproject/web-components#29]
Provide a better editor experience to edit links. E.g. see what Google Docs does, or other comparable editors.

This should be pluggable so that the user can define a custom editor for dates/times etc.

**Comment by TC5022** [comment]
@dselman Could you please specify some functionalities required in this editor? Since we can already edit, copy and remove the links, what else should be added?

**Comment by dselman** [comment]
I think we can close this - I agree the existing functionality is sufficient.
