### ISSUE TITLE
Addition of Heading 4, Heading 5, and Heading 6 and updation of existing headings

### ISSUE THREAD

**Issue by d-e-v-esh** [accordproject/web-components#293]
# Feature Request 🛍️

Updating the Existing Heading Size and addition of Heading 4, Heading 5 and, Heading 6 into the dropdown menu.

## Use Case

`Heading 1` = 25px => Stays the same
`Heading 2` = 25px => Left-aligned to differentiate from H1
`Heading 3` = 20px
`Heading 4` = 18px
`Heading 5` = 16px
`Heading 6` = 14px => Same size as a normal paragraph, All capital letters, The same text formatting as the text used in Page Break:

![110824137-c516a900-8260-11eb-9ba8-a5a0457bcc8b](https://user-images.githubusercontent.com/59534570/110834861-1441f580-82c4-11eb-886d-13c233357f63.png)

**Comment by d-e-v-esh** [comment]
@Michael-Grover Hey, I created the Headings issue. 👍

**Comment by d-e-v-esh** [comment]
@Michael-Grover Something seems wrong with `Heading 6`. You can see it in the main demo. It looks something like this:


![chrome_guwTC9C155](https://user-images.githubusercontent.com/59534570/111041591-e349f800-845e-11eb-8130-f5c226a1c6fc.png)

You can see the distance between `H6` and `Fin` is much larger. Extra margin is being applied somewhere that I can't find.
And the margin gets significantly larger as the font size grows.
After implementing the above, `Heading 5` looks totally normal like this:

![chrome_qmlSTrFRFM](https://user-images.githubusercontent.com/59534570/111041651-43409e80-845f-11eb-8869-04dd908f8507.png)

and `Heading 6` looks like this:

![chrome_rj7eIloc88](https://user-images.githubusercontent.com/59534570/111041660-55bad800-845f-11eb-8b45-e9fe0d60c22f.png)

and if I increase the font size then it looks like this:


![chrome_sjuByWZC1J](https://user-images.githubusercontent.com/59534570/111042193-2ce81200-8462-11eb-9eec-579c3d313421.png)

This is happening only with `Heading 6`. Do you have any idea what could be causing the problem?

**Comment by Michael-Grover** [comment]
@d-e-v-esh sorry, I'm not sure. Someone who is more familiar with CSS like @irmerk or @DianaLease may know

**Comment by d-e-v-esh** [comment]
@Michael-Grover This problem was occurring because of the [user agent stylesheet](https://stackoverflow.com/questions/12582624/what-is-a-user-agent-stylesheet). Overriding the default styles by adding margin properties fixes the problem.

**Comment by akk312000** [comment]
I would like to contribute and fix the issue.
Can you guide me how should I go forward into solving this issue.

**Comment by irmerk** [comment]
@akk312000 @d-e-v-esh is working on this already as you can see in the Issue.

@d-e-v-esh I still haven't had time to look into this to give you feedback, sorry. I'm hoping to very soon.

**Comment by d-e-v-esh** [comment]
@irmerk That is totally fine 👍
