### ISSUE TITLE
Clickable area of "insert image" and "page break" is much smaller than other items in the formatting toolbar

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#318]
# Bug Report 🐛

For some reason, the clickable area of the "insert image" and "page break" icons in the formatting toolbar is much smaller than the clickable area of all of the other icons in the formatting toolbar. This makes the icons harder to click, and is visually inconsistent.

The red squares roughly show the clickable areas:
![image](https://user-images.githubusercontent.com/40569793/112326777-31df6980-8c8b-11eb-9067-639a4d85b8d2.png)

another comparison:

![image](https://user-images.githubusercontent.com/40569793/112327218-9d293b80-8c8b-11eb-8b00-04afe9f218d8.png)
![image](https://user-images.githubusercontent.com/40569793/112327277-aadec100-8c8b-11eb-86cc-ee498aaf6dfd.png)
It's hard to see, but there's a gray rounded square that appears when hovering over the clickable area of an icon. The above images show that the gray square is larger for most icons like "hyperlink", but very small for icons like "page break"

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I would like to work on this issue. Please assign this to me.

**Comment by Michael-Grover** [comment]
@K-Kumar-01 thanks, I've assigned you

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I have opened a PR for the issue. Let me know if there are any changes required.
