### ISSUE TITLE
contract-editor error onChange: Cannot read property 'focus' of null

### ISSUE THREAD

**Issue by rsilva-uw** [accordproject/web-components#335]
I'm having the same issue over and over again. When I initialize the contract editor, same code as it is in the storybook i keep getting this crash error: 

![image](https://user-images.githubusercontent.com/83576366/116988808-cd232000-acc8-11eb-813d-6f6a50d20739.png)

I went further ahead and saw the same error on the storybook, however, in this environment the error is suppressed, which in developmnet it is not, and its pretty hard to develop with this always popping up:

![image](https://user-images.githubusercontent.com/83576366/116989645-eaa4b980-acc9-11eb-8376-a87b5370cb77.png)

**Comment by dselman** [comment]
Interesting, thanks. The `Refused to set unsafe header` message appears to be a Chrome issue (could be harmless?).
https://stackoverflow.com/questions/54828208/how-to-resolve-refused-to-set-unsafe-header-user-agent-in-javascript

It might be getting triggered by this code:
https://github.com/accordproject/cicero/blob/fe8e25264763689dd57cf2ff0933f5c5a6d82059/packages/cicero-core/src/templatelibrary.js#L141

Can you help me reproduce the other error you are seeing?

**Comment by rsilva-uw** [comment]
Uhh, I don't think that error is a problem per se. My main issue is that "Cannot read property "focus" of null" which is both happening here: https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor and when I'm developing. As I said, in the storybook the error is supressed, but in a development environment the issue keeps popping up and crashing the app.

**Comment by dselman** [comment]
> Uhh, I don't think that error is a problem per se. My main issue is that "Cannot read property "focus" of null" which is both happening here: https://ap-web-components.netlify.app/?path=/story/contract-editor--contract-editor and when I'm developing. As I said, in the storybook the error is supressed, but in a development environment the issue keeps popping up and crashing the app.

Thanks, that helps. I see the error occur once in the storybook (on load?) and then it does not reoccur. The stack is:

```
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating '_.selection.focus')
	onChange (main.4b782334bb7dec72a581.bundle.js:1:231564)
	(anonymous function) (vendors~main.4b782334bb7dec72a581.bundle.js:2:184859)
	(anonymous function) (vendors~main.4b782334bb7dec72a581.bundle.js:2:188069)
	Mj (vendors~main.4b782334bb7dec72a581.bundle.js:2:4271927)
	(anonymous function) (vendors~main.4b782334bb7dec72a581.bundle.js:2:187984)
	(anonymous function) (main.4b782334bb7dec72a581.bundle.js:1:100600)
	(anonymous function) (vendors~main.4b782334bb7dec72a581.bundle.js:2:113902)
	promiseReactionJob
```

Which implies that the `onChange` handler

**Comment by dselman** [comment]
Fix has been released https://github.com/accordproject/web-components/releases/tag/v0.98.0

**Comment by rsilva-uw** [comment]
Nice. In the meantime I forked the repo to have more freedom in changes to my needs.
