### ISSUE TITLE
Adding Background In Inline Code

### ISSUE THREAD

**Issue by d-e-v-esh** [accordproject/web-components#341]
# Feature Request 🛍️

Inline code is used to insert code snippets in the middle of the normal text line.
In the markdown-editor, it currently looks like this:

![image](https://user-images.githubusercontent.com/59534570/117575701-a6b61800-b100-11eb-9bbb-259568bc7863.png)

As you can see, it is really difficult to identify the bit of inline code. This is because the only thing differentiating the normal text from inline code is the **_font_** we are using.

This is how other text editors render inline code:

### Notion:

![Notion_Heq5CO1IUA](https://user-images.githubusercontent.com/59534570/117576072-0d880100-b102-11eb-8c12-986f03989834.png)

### Typora:

![Typora_EHlTLsAFCn](https://user-images.githubusercontent.com/59534570/117576053-ff39e500-b101-11eb-8e2e-ba622af40aef.png)

### GitHub Markdown:

![chrome_KpTkf7I09J](https://user-images.githubusercontent.com/59534570/117576091-20023a80-b102-11eb-9986-90a71e3bd138.png)

### StackOverflow:

![chrome_vw7NBxjxlV](https://user-images.githubusercontent.com/59534570/117576106-2e505680-b102-11eb-98b6-ea13dd838802.png)

## Implementation

 - Adding a slightly grey background would make it much easier for us to identify what part of the line is inline code.
 - We can also discuss if we want to change the font color to something different than the normal text.
 - It can be a little less dark to create contrast between the two or it can be something totally different.

**Comment by K-Kumar-01** [comment]
@Michael-Grover 
I would like to work on the issue. I have already prepared the code for it. Can I make a PR?

**Comment by Michael-Grover** [comment]
sure, unless @d-e-v-esh would like to. I assume @d-e-v-esh made the issue because he wants to work on it? @d-e-v-esh what do you think?

**Comment by d-e-v-esh** [comment]
@Michael-Grover Yes, I want to work on this. Do you have any suggestions for the color of the `inline code` text? Or should I do what I feel is the best?

**Comment by Michael-Grover** [comment]
@d-e-v-esh let's try black text for now. I'll assign the issue to you since you created it.

**Comment by Michael-Grover** [comment]
@K-Kumar-01 @d-e-v-esh feel free to share code and collaborate on the issue
