### ISSUE TITLE
Heading Markdown Shortcut WYSIWYG (What You See Is What You Get)

### ISSUE THREAD

**Issue by d-e-v-esh** [accordproject/web-components#346]
# Feature Request 🛍️

This feature is a small part of #321.

As requested in issue #321, it contains a lot of small features and was decided to be implemented incrementally one by one and use issue #321 to track the changes.

## Use Case

This would help us insert headings in our documents by just using the `#`  like this:

![H7sygSBx7J](https://user-images.githubusercontent.com/59534570/118137376-c57b1e00-b422-11eb-92e5-3c240017ad83.gif)

**Comment by irmerk** [comment]
Use https://github.com/accordproject/web-components/pull/347 as reference when starting this.
