### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by HarshJaiswani** [accordproject/web-components#363]
#Update ReadMe for local envirnoment setup

In readme it states to run lerna clean and lerna bootstrap
which does not works fine
rather npm run repoclean which correspondes to lerna clean and
npm run bootstrap which corresponds to lerna bootstrap works fine

@irmerk  This is my first time in open source please guide me if something to correct and how to procede

**Comment by mttrbrts** [comment]
Congratulations on opening your first issue @HarshJaiswani !

The scripts in `package.json` mean that `npm run repoclean` and `lerna clean` are equivalent, providing that you have lerna installed globally (which is part of the installation instructions).

It appears that you have some other issue related to running lerna.
