### ISSUE TITLE
Add support for tables

### ISSUE THREAD

**Issue by dselman** [accordproject/web-components#39]
Many markdown files contain tables. It would be very useful for the editor to support these files.

**Describe the solution you'd like**
UI to render and edit tables.

**Additional context**

We will need to extends`accordproject/markdown-common` and the CommonMark DOM to represent tables, as well as the other transforms to support them.

Slate tables demo: https://www.slatejs.org/examples/tables
Table in commonmark discussion: https://talk.commonmark.org/t/tables-in-pure-markdown/81/9
GFM: https://github.github.com/gfm/#tables-extension-

**Comment by TC5022** [comment]
May I work on this issue @dselman?

**Comment by arpit-maurya** [comment]
@dselman @irmerk @DianaLease @jeromesimeon  Can you assign this issue to me

**Comment by TC5022** [comment]
I am still working on this issue.
