### ISSUE TITLE
SHIFT+Enter in Blockquote

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#41]
**Describe the bug**
A user cannot create a line break _within_ a blockquote.

**To Reproduce**
1. Go to the [live demo](https://accordproject-markdown-editor.netlify.com/)
2. Click at the end of the first paragraph
3. Press `Enter` and type something
4. Format as a blockquote with the toolbar
5. Press `SHIFT + Enter`
6. A new blockquote is made

**Expected behavior**
Pressing `SHIFT + Enter` inside a block quote should create a new line _within_ the blockquote

**Comment by dselman** [comment]
Editor support for SHIFT-ENTER to insert a markdown linebreak (`<br/>` in HTML) has been added. Closing this - please create new issues if this is insufficient with additional details.
