### ISSUE TITLE
Twitter icon is old.

### ISSUE THREAD

**Issue by Ayush9026** [accordproject/web-components#415]
Twitter icon is old marked in pic below replace with new one 'x' .
![accord project front page](https://github.com/accordproject/web-components/assets/114745463/a3ec78c8-554e-498f-b97b-7d51042a62e1)

**Comment by vatsalllll** [comment]
I want to work on this and fix this issue, by replacing the old logo with the new "X" logo.

**Comment by subhajit20** [comment]
Hey @Ayush9026 can you point out the specific file from where I can get the old Twitter icon?
Then it will be easier for me to replace the old one with new one.

**Comment by mttrbrts** [comment]
Thanks for the report @Ayush9026 @subhajit20. Our website administrator has fixed the logo.
