### ISSUE TITLE
Hyperlink Modal Disrupts History

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#42]
**Describe the bug**
A user cannot undo a link if forwarding through a hyperlink modal in history

**To Reproduce**
1. Go to the [live demo](https://accordproject-markdown-editor.netlify.com/)
2. Create new empty paragraph
3. Select hyperlink, type in a word and a hyperlink
4. Navigate back in history
5. Navigate forward, see hyperlink modal appear, navigate forward again
6. Cannot navigate backward in history anymore

**Expected behavior**
History should not be interrupted by the hyperlink modal

**Comment by Cronus1007** [comment]
> 4. Navigate back in history
> 5. Navigate forward, see hyperlink modal appear, navigate forward again
> 6. Cannot navigate backward in history anymore

PLzzz provide a little more context for these steps.

**Comment by Michael-Grover** [comment]
I'm not able to replicate this bug (macbook, Google Chrome)

**Comment by Michael-Grover** [comment]
It looks like the issue may no longer exist. @irmerk can you confirm?

**Comment by irmerk** [comment]
Correct, this was fixed at some point.
