### ISSUE TITLE
Dragging Image Duplicates 

### ISSUE THREAD

**Issue by sachdeva-shrey** [accordproject/web-components#45]
**Describe the bug**
Selecting and dragging an image within the Editor duplicates it.

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Click on the Concerto Model Image _or_ insert a new one
3. Drag it to a new position
4. The image is duplicated

**Expected behavior**
Only the position of the image should be changed.

**Screenshots**
![Markdown Editor (5)](https://user-images.githubusercontent.com/47667325/79165199-3d31e000-7e00-11ea-95a5-5fec64483719.gif)

**Comment by Cronus1007** [comment]
@irmerk Since the issue still exists so shall I take over this issue.

**Comment by Cronus1007** [comment]
@irmerk This issue doen't exist any more.
