### ISSUE TITLE
Line Break not preserved on paste

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#46]
**Describe the bug**
When copying multiple lines and then pasting them, the line breaks are not preserved.

**To Reproduce**
1. Go to the [demo](https://accordproject-markdown-editor.netlify.com/)
2. Select "This is a\
hard break."
3. Press Mod+C to copy
4. Select somewhere in the middle of "This is a\
hard break."
5. Press  Mod+P to paste
6. See that the line break from the copied text has not been preserved.

**Expected behavior**
The line break should be preserved, such that there are now three lines in the section.

See Loom video
https://www.loom.com/share/cf0dd7088d964e9a93a5259deccfd190

**Comment by K-Kumar-01** [comment]
@Michael-Grover @irmerk 
Is the issue still open?
I tried copy-pasting but was unable to replicate the issue. I am attaching a video below.
https://www.loom.com/share/f488267401f1460da06e0092699898a4

**Comment by Michael-Grover** [comment]
@K-Kumar-01 I can no longer replicate the issue. Thanks for pointing out.
