### ISSUE TITLE
Hyperlink Modal Persists with Shift Tabbing Out

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#47]
**Describe the bug**
A user goes through extra steps to close the hyperlink modal

**To Reproduce**
1. Go to the [live demo](https://accordproject-markdown-editor.netlify.com/)
2. Select the existing hyperlink
3. <kbd>SHIFT</kbd> + <kbd>TAB</kbd> twice
4. Type or press <kbd>ENTER</kbd>
5. Hyperlink modal does not close

**Expected behavior**
Modal should close if user is not interacting with it

**Comment by whyang0808** [comment]
Hi, may I pick this up?
