### ISSUE TITLE
SHIFT+Enter in List Item

### ISSUE THREAD

**Issue by sachdeva-shrey** [accordproject/web-components#49]
**Describe the bug**
Currently, a new list item is created on pressing `Enter` or`Shift+Enter`. The user should be able to add a new line wrapped within the same list item on pressing `Shift+Enter`.

**To Reproduce**
1. Go to [the demo](https://accordproject-markdown-editor.netlify.app/)
2. Go the end of any list item
3. Press `Enter`/`Shift+Enter`
4. See the behaviour

**Expected behavior**
The user should be allowed to add a new line to the same list item on pressing `Shift+Enter`. 

**Related Issues**
Issue https://github.com/accordproject/markdown-editor/issues/335
PR https://github.com/accordproject/markdown-editor/pull/370

**Comment by dselman** [comment]
Editor support for SHIFT-ENTER to insert a markdown linebreak (`<br/>` in HTML) has been added. Closing this - please create new issues if this is insufficient with additional details.
