### ISSUE TITLE
Display a message in hyperlink modal to indicate that the link is copied

### ISSUE THREAD

**Issue by nik72619c** [accordproject/web-components#50]
**Is your feature request related to a problem? Please describe.**
Currently, when a user clicks on the copy button to copy the link to the clipboard, there is no message which tells the user that the link is copied.

**Describe the solution you'd like**
A simple message could be displayed in the modal indicating that the link is copied

**Comment by irmerk** [comment]
Work has started: https://github.com/accordproject/markdown-editor/pull/391

**Comment by sahalsaad** [comment]
Hi, in Hacktoberfest profile it show below status for my PR to this repo.
![image](https://user-images.githubusercontent.com/22321353/95028979-390fbc80-06d7-11eb-87f0-31479fad246f.png)
