### ISSUE TITLE
UI Realignment

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#51]
In the Slate migration, we have strayed a bit from the original editor styling. We need to ensure this is back on to specification, both in `cicero-ui` and in a parent component.

What should the “_out of the box_” style look like if someone wants to just import this component and be done with it?

We need to decide what style / design we want in `markdown-editor` (`RichTextEditor`) _and_ `cicero-ui` (`ContractEditor`)

**NOTE**: Code addressing this issue should be overridable via CSS by a parent component.

**Comment by justinclanglinais** [comment]
I'd like to work on this issue!

**Comment by irmerk** [comment]
@justinclanglinais any update on this? Need any help?
