### ISSUE TITLE
List Formatting Not Preserved in Headings

### ISSUE THREAD

**Issue by sachdeva-shrey** [accordproject/web-components#54]
**Describe the bug**
Headings when converted to lists, do not preserve the list formatting i.e. the list item number/bullets are not shown. Please see the screenshot below.

**To Reproduce**
1. Go to [the demo](https://accordproject-markdown-editor.netlify.app/).
2. Select any heading
3. Select Numbered/Bulleted list from the Toolbar Menu
4. See the bug

**Expected behavior**
The heading should be converted to a list item and converted to a `Paragraph` node. Check the expected behaviour here:
https://www.slatejs.org/examples/richtext

**Screenshots**
![Markdown Editor (10)](https://user-images.githubusercontent.com/47667325/80820392-628e5e80-8bf4-11ea-941d-3676fbfce108.gif)

**Comment by naveen8801** [comment]
hiii @irmerk   , can i work on this issue ?

**Comment by gatij10** [comment]
Is this issue still open? May I solve the bug ?

**Comment by gatij10** [comment]
@irmerk Is this issue still open? May I solve the bug ?

**Comment by gatij10** [comment]
@irmerk I have opened a PR for this issue. Let me know if there are any changes required
