### ISSUE TITLE
Library Details button serves modal

### ISSUE THREAD

**Issue by irmerk** [accordproject/web-components#65]
# Related Issues
- Issue accordproject/cicero-ui#6
- Issue [#24](https://github.com/accordproject/template-studio-v2/issues/24) in TSv2

## Tasks
- Create functionality to serve up specific template in a details modal.

**Comment by Cronus1007** [comment]
@DianaLease Any updates regarding this issue.

**Comment by Michael-Grover** [comment]
@irmerk  
> elit-altum it might, we haven't revisited this concept in a bit. @Michael-Grover do we have a clear goal in mind with this as a feature? We may not have a use for it anymore.

@irmerk I don't even remember what this feature is, and even after looking at the linked issues I'm a bit confused. was the goal to have a modal with details about the clause template?

Maybe we can close this issue and https://github.com/accordproject/template-studio-v2/issues/24, what do you think?

**Comment by irmerk** [comment]
Hmm yeah I think you're right @Michael-Grover that this was about a modal with details, but it was pretty much in the context of TSv2. So I think we can sunset this.
