### ISSUE TITLE
Formulae UI

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#69]
Add support for computed variables in the Cicero UI.
Contact @Michael-Grover with your email address to get access to the clickable prototype on invision
https://projects.invisionapp.com/d/main#/console/16741009/406893195/preview

---

https://projects.invisionapp.com/d/main#/console/16741009/406893195/preview
![image](https://user-images.githubusercontent.com/40569793/78183374-cd9e1700-7435-11ea-8dce-c1754ea42f13.png)

---

https://projects.invisionapp.com/d/main#/console/16741009/406893196/preview
![image](https://user-images.githubusercontent.com/40569793/78183392-d42c8e80-7435-11ea-8c91-afbb8cd1f9ec.png)

---

https://projects.invisionapp.com/d/main#/console/16741009/406893194/preview
![image](https://user-images.githubusercontent.com/40569793/78183430-e3abd780-7435-11ea-8e58-7c295157248b.png)

---

https://projects.invisionapp.com/d/main#/console/16741009/406893193/preview
![image](https://user-images.githubusercontent.com/40569793/78183453-ee666c80-7435-11ea-9306-1880aa345950.png)

---

https://projects.invisionapp.com/d/main#/console/16741009/406893192/preview
![image](https://user-images.githubusercontent.com/40569793/78183514-05a55a00-7436-11ea-9b12-becd06b5b394.png)

**Comment by jeromesimeon** [comment]
@Michael-Grover 👍 Let's call those "Formulas" from now on?

**Comment by irmerk** [comment]
@Michael-Grover is this what you'd have in mind with the new variable UI?

<img width="642" alt="Screen Shot 2020-06-09 at 4 45 43 PM" src="https://user-images.githubusercontent.com/36460856/84197949-ca945800-aa70-11ea-9a4c-e85fa83777c0.png">

**Comment by Michael-Grover** [comment]
yeah that looks good
