### ISSUE TITLE
Pressing enter on the markdown editor scrolls to top

### ISSUE THREAD

**Issue by elit-altum** [accordproject/web-components#91]
# Bug Report 🐛

Upon pressing enter on the markdown editor storybook demo, the editor scrolls to the top.

## Expected Behavior

The editor should be at its place.

## Possible Solution

I think this could be an issue similar to https://github.com/accordproject/markdown-editor/pull/388

## Steps to Reproduce

1. Visit the Demo
2. Place cursor on the editor
3. Press Enter
4. The screen will scroll to the top

### Desktop
 - OS: Windows 10
 - Browser: Firefox developer edition

## Screenshot
![Scroll-error](https://user-images.githubusercontent.com/41413622/82155191-b81f6800-9890-11ea-939b-87504ff3b94f.gif)

**Comment by elit-altum** [comment]
@irmerk is this expected behavior?
 And it also seems like the editor is crashing if I use any shortcuts like Ctrl + K etc. Are you able to reproduce this ?

**Comment by irmerk** [comment]
Yeah I can reproduce it. However, I can't reproduce the shortcuts crashing the editor.

**Comment by justinclanglinais** [comment]
Hi, I can't reproduce this error.

**Comment by irmerk** [comment]
I can't either. Unsure what changed since May. Closing.
