### ISSUE TITLE
Hyperlink tool can create two separate hyperlinks

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#96]
# Bug Report 🐛
It is possible to create two separate hyperlinks with the hyperlink tool

## Expected Behavior
Only the highlighted area should become a hyperlink

## Steps to Reproduce
https://www.loom.com/share/7014c3e0850c486780ae486e96345355
1. Triple click on a line of text
2. Press cmd+k to create a hyperlink
3. Enter a url
4. Save the hyperlink
5. Now there are two hyperlinks. One hyperlink is the selected area, and another hyperlink is part of the line after the selected area

**Comment by irmerk** [comment]
This could likely be a check to see if the selection spans multiple nodes at the top level, either on submission or on opening of the modal (through the button or keyboard shortcut).

**Comment by amanda-ariyaratne** [comment]
This issue seems to be coming from Slate. Can you please elaborate your proposed solution. @irmerk I don't think checking at the top level could be enough because the nodes can be in a nested structure.

**Comment by irmerk** [comment]
@amanda-ariyaratne hmm interesting... I think my suggestion could still be good because the check would not be concerned with if something is nested. It would check if the beginning and end of a selection are in the same root node.

![Screen Shot 2020-10-19 at 2 51 06 PM](https://user-images.githubusercontent.com/36460856/96498809-8a14ca00-121a-11eb-9c05-272243d4371a.png)

**Comment by amanda-ariyaratne** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/28347418/96677970-53f85700-138e-11eb-836ac5389f57b1f6.png)

So in this example (attached screenshot), 

If I double click and highlight the second numbered list item the selection is
```
{
  "anchor": 
     {
        "path": [2,1,0,0],
        "offset":0
     },
  "focus":
     {
       "path": [2,1,0,0],
       "offset":3
     }
}
```

If I triple click the same the selection is
```
{
  "anchor": 
     {
        "path": [2,1,0,0],
        "offset":0
     },
  "focus":
     {
       "path": [2,2,0,0],
       "offset":0
     }
}
```

A solution might be possible still. But I'm sure how complex the nesting can get.

Also the demo given by [Slate](https://www.slatejs.org/examples/links) produces the same problem. Try to select the first line by a triple click and add a hyperlink. 

I'm willing to work on this so if you have any more ideas let me know.

**Comment by irmerk** [comment]
@amanda-ariyaratne good point on it being in Slate, I should have looked when you mentioned it was coming from there. There doesn't _appear_ to be any [Issue on it in their repository](https://github.com/ianstormtaylor/slate/issues?q=is%3Aissue+is%3Aopen+link).

I would think the solution should be from down in Slate. So I think marking this as Won't Fix and opening an issue in their repository is the best route.

@amanda-ariyaratne if you're interested in working on it, I recommend opening the issue in their repo and working on it there. Would you be fine with at least opening the issue in their repo?

**Comment by amanda-ariyaratne** [comment]
@irmerk yeah sure I'll open up a new issue in Slate, if it isn't already there.
I'm new to this so wanted to make sure there's nothing to be done from this side. Thanks.

**Comment by Cronus1007** [comment]
@irmerk Shall I implement this issue.

**Comment by Cronus1007** [comment]
@irmerk @Michael-Grover Have a look upon this 
![78d0a0cc-63ff-4997-bddb-04e7bf748bf3](https://user-images.githubusercontent.com/56436023/110851082-976c4700-82d6-11eb-90c1-d209727268a2.gif)

**Comment by irmerk** [comment]
What am I looking for? Can you explain some more context?

**Comment by Cronus1007** [comment]
@irmerk I guess the problem is only with lists.Here heading and paragraphs worked a quite better than the lists.

**Comment by Michael-Grover** [comment]
In the original recording I shared in the description, it shows there is also a problem when you highlight an entire line that is above a heading. Even though the heading is not highlighted, it becomes a separate link. @Cronus1007 thanks for catching that this bug happens with lists too.

**Comment by Michael-Grover** [comment]
I'm not able to reproduce this bug, so I am closing the issue
