### ISSUE TITLE
Style section of formatting toolbar flashes when editing a hyperlink

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/web-components#97]
# Bug Report 🐛
Style section of formatting toolbar flashes when editing a hyperlink

## Expected Behavior
The style section of the formatting toolbar should show the style of the highlighted area

## Steps to Reproduce
1. Start creating a hyperlink. The style section of the formatting toolbar will switch between different styles with every keystroke
https://www.loom.com/share/7014c3e0850c486780ae486e96345355

**Comment by irmerk** [comment]
I believe it also will show as blank when over certain elements (variables in `cicero-ui` I think), so this could be improved.

**Comment by sahalsaad** [comment]
I'll try to fix this issue.
